# Generated by Django 3.1.5 on 2021-01-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sold', models.CharField(max_length=200)),
                ('in_stock', models.IntegerField()),
                ('date_ordered', models.CharField(max_length=200)),
                ('date_purchased', models.CharField(max_length=200)),
            ],
        ),
    ]
